### ISSUE TITLE
Put the link of website in README.md

### ISSUE THREAD

**Issue by Shantanu-Meta** [rohit09-birth/ARCADE#1]
There is no link that how this website will look like.

**Comment by Tapo41** [comment]
I want to contribute under diversion 2k23

**Comment by rohit09-birth** [comment]
> There is no link that how this website will look like.

Okay fine we will look into that for sure but you are requested to join a discord meet this evening or night whatever be it  so that the next day problem can be discussed

**Comment by rohit09-birth** [comment]
> I want to contribute under diversion 2k23

Okay so we will be having a discord meeting tonight, please join it so that we can brief you on the needs of the whole day

**Comment by rohit09-birth** [comment]
Drop your number so that we can have the meet

**Comment by rohit09-birth** [comment]
Drop your number so that we can have the meet

**Comment by rohit09-birth** [comment]
.SOLVED
