### ISSUE TITLE
Fix the front end , it has some bugs

### ISSUE THREAD

**Issue by rohit09-birth** [rohit09-birth/ARCADE#3]
front end is not linking any underlying pictures

**Comment by rt-001** [comment]
I will like to work on this.

**Comment by rt-001** [comment]
is it still open?

**Comment by rohit09-birth** [comment]
> is it still open?

this particular issue is not existing but we have many more issues in the front end

**Comment by rohit09-birth** [comment]
> > is it still open?
> 
> this particular issue is not existing but we have many more issues in the front end

you can drop your contact so that we can assign you the specific task

**Comment by rt-001** [comment]
> > > is it still open?
> > 
> > 
> > this particular issue is not existing but we have many more issues in the front end
> 
> you can drop your contact so that we can assign you the specific task

github = > rt-001
discord=> rt_001
gmail=>romittiwari100@gmail.com

**Comment by Hitanshi-Singh** [comment]
hello, I want to work on the front end. I have fixed some issues. Can I make a PR?

**Comment by rohit09-birth** [comment]
Yes you can but do one thing , join the under mentioned official project
group where the project requirements are discussed so that that task can be
assigned everyday
WE HAVE ONLY 4 DAYS LEFT AS OF DIVERSION


https://chat.whatsapp.com/GuGow6QaQWdHWVNxwdJKTZ

**Comment by rohit09-birth** [comment]
bugs were all cleared
